package me.kqlqk.behealthy.tgbot.service.command;

public enum CommandState {
    BASIC,

    LOGIN_WAIT_FOR_DATA,

    REGISTRATION_WAIT_FOR_DATA,

    ADD_FOOD_WAIT_FOR_DATA,
    ADD_FOOD_WAIT_FOR_DATA_CALLBACK,

    CHANGE_KCAL_GOAL_WAIT_FOR_CHOOSING,
    CHANGE_KCAL_GOAL_WAIT_FOR_CHOOSING_KCAL,
    CHANGE_KCAL_WAIT_FOR_DATA,

    RETURN_TO_BODY_CONDITION_MENU,

    SET_BODY_CONDITION_WAIT_FOR_FAT_PERCENT,
    SET_BODY_CONDITION_WAIT_FOR_GENDER,
    SET_BODY_CONDITION_WAIT_FOR_ACTIVITY,
    SET_BODY_CONDITION_WAIT_FOR_GOAL,
    SET_BODY_CONDITION_WAIT_FOR_DATA,

    DELETE_ALL_PHOTOS_WAIT_FOD_CHOOSING,

    RETURN_TO_WORKOUT_SERVICE_MENU,

    SET_WORKOUT_WAIT_FOR_DATA,

    ADD_EXERCISE_WAIT_FOR_DATA,

    REMOVE_EXERCISE_WAIT_FOR_DATA,

    CHANGE_EXERCISE_WAIT_FOR_DATA,

    LOGS_WAIT_FOR_CHOOSING,

    SEND_MESSAGE_WAIT_FOR_MESSAGE,

    WAIT_FOR_PHOTO
}
